apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: khalyqmarket-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
  - host: www.khalyqmarket.tvha23.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-external
            port:
              number: 80
